# Generated by Django 5.2.11 on 2026-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilephoto',
            field=models.CharField(default='', max_length=500),
        ),
    ]
